[tool.poetry]
name = "CBC Utils"
version = "0.1.0"
description = "Utilities for the Christmas Bird Count"
authors = ["Liz Stanley <lizmstanley@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "1.0.1"
requests = "^2.32.3"
toml = "^0.10.2"